---
- name: To create a  Prod resource group in azure
  hosts: localhost
  tasks:
    - name: Create Production Resource Group
      azure_rm_resourcegroup:
        name: prod-rg
        location: west europe
   
   
- name: To create a  Dev resource group in azure
  hosts: localhost
  tasks:
    - name: Create Dev Resource Group
      azure_rm_resourcegroup:
        name: prod-rg
        location: west europe
  
