---
- name: To create a resource group in azure
  hosts: localhost
  tasks:
    - name: Create Production Resource Group
      azure_rm_resourcegroup:
        name: prod-rg
        location: west europe
      
      
    - name: Create virtual network
      azure_rm_virtualnetwork:
      resource_group: prod-rg
        name: prod-vnet
        address_prefixes: "10.0.0.0/16"
        
    - name: Add subnet
      azure_rm_subnet:
      resource_group: prod-rg
        name: linux-subnet
        address_prefix: "10.0.1.0/24"
        name: windows-subnet
        address_prefix: "10.0.2.0/24"
      virtual_network: prod-vnet
   
   

  
