---
- name: To create a resource group in azure
  hosts: localhost
  tasks:
    - name: Create Production Resource Group
      azure_rm_resourcegroup:
        name: prod-rg
        location: west europe
      register: rg
    - debug:
        var: rg
        
  tasks:
    - name: Create Dev Resource Group
      azure_rm_resourcegroup:
        name: dev-rg
        location: west europe
      register: rg
    - debug:
        var: rg
