---
- name: To create a resource group in azure
  hosts: localhost
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: prod-rg
        location: west europe
    
    - name: Create a virtual network
      azure_rm_virtualnetwork:
        resource_group: prod-rg
        name: prod-vnet
        address_prefixes_cidr: "10.0.0.0/8"
    
    - name: Create a subnet
      azure_rm_subnet:
        resource_group: prod-rg
        virtual_network_name: prod-vnet
        name: linux-subnet
        address_prefix_cidr: "10.0.1.0/24"
    
    - name: Create a public ip address
      azure_rm_publicipaddress:
        resource_group: prod-rg
        name: prod-pip
        allocation_method: dynamic

    - name: Create a Secuirty group    
      azure_rm_securitygroup:
        resource_group: prod-rg
        name: prod-srg
        purge_rules: yes
        rules:
          - name: 'AllowSSH'
            protocol: Tcp
            source_address_prefix: "*"
            destination_port_range: 22
            access: Allow
            priority: 101
            direction: Inbound
          - name: 'Allow-HTTP-HTTPS'
            protocol: Tcp
            source_address_prefix: "*"
            destination_port_range:
              - 80
              - 443
            access: Allow
            priority: 102

    - name: Create a network interface using existing security group and public IP
      azure_rm_networkinterface:
        name: testlinux-nic
        resource_group: prod-rg
        virtual_network: prod-vnet
        subnet_name: linux-subnet
        security_group: prod-srg
        ip_configurations:
          - name: ipconfig1
            public_ip_address_name: prod-pip
            primary: True