---
- include_vars: variables.yaml
- include_vars: SPN_AzureAD_Automation_Vault.yaml
  no_log: yes

- name: "Importing Dev Subscriptions variables"
  include_vars: roles/AzureResourceGroup/vars/variables_dev.yaml
  when: Subscription_Name == "Azure_Dev"

- name: "Importing Test Subscriptions variables"
  include_vars: roles/AzureResourceGroup/vars/variables_test.yaml
  when: Subscription_Name == "Azure_Test"

- name: "Importing Prod Subscriptions variables"
  include_vars: roles/AzureResourceGroup/vars/variables_prod.yaml
  when: Subscription_Name == "Azure_Prod"

- name: "Importing Azure Subscriptions variables"
  include_vars: roles/AzureResourceGroup/vars/variables_Azure.yaml
  when: Subscription_Name == "Azure"

- import_tasks: Create_ResoureGroup.yaml

- name: "Importing Contributor-TetraPak Role variables"
  include_vars: roles/AzureResourceGroup/vars/Contributor.yaml
  when: Role_Name == "Contributor"
  
#- name: "Importing Owner Role variables"
#  include_vars: roles/AzureResourceGroup/vars/owner.yaml
#  when: Role_Name == "Owner"

#- name: "Importing Contributor Role variables"
#  include_vars: roles/AzureResourceGroup/vars/Contributor.yaml
#  when: Role_Name == "Contributor"

- import_tasks: Role_Assignment.yaml
